---
title: " Novoalign Testing Report"
author: "Muhamad Amir Hafizin"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
output:
   ioslides_presentation:
pdf_document:
html_document:
theme: united
---

*****

### ART vs Novoalign

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/novamapped.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

### ART vs BWA
```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/bwa.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****


### NOVO vs BWA

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/novoandbwa1.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

### NOVOALIGN and BWA MAPPED 

#### Novo

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/novomapl.csv",header=TRUE)
library("knitr")
kable(tab)
```
*****

#### BWA


```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/bwamapl.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

#### NOVO AND BWA


```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/novobwa2.csv",header=TRUE)
library("knitr")
kable(tab)
```
*****

#### NOVOALIGN and BWA MAPPED PERCENTAGE

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/percentmapped.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

### NOVOALIGN and BWA MAPPED CHROMOSOEM
#### Novo

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/novochrl.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

#### BWA

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/bwachr.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

#### NOVO AND BWA

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/novobwa2.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

#### NOVOALIGN and BWA MAPPED CHROMOSOME PERCENTAGE

```{r,echo= FALSE, results="asis"}
tab= read.csv("/export/home/amirh/novoalign_testing/bedtool/cigar/bwanovo/percentchr.csv",header=TRUE)
library("knitr")
kable(tab)
```

*****

